# Generated by Django 5.1.4 on 2026-06-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('hero', 'CTA Головна (hero)'), ('contact', 'Контакти'), ('model', 'Заявка на модель'), ('configurator', 'Конфігуратор'), ('faq', 'FAQ fallback')], default='contact', max_length=20, verbose_name='Тип форми')),
                ('name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('gdpr_consent', models.BooleanField(default=False, verbose_name='Згода GDPR')),
                ('equipment_tier', models.CharField(blank=True, max_length=20, verbose_name='Комплектація')),
                ('configurator_data', models.JSONField(blank=True, null=True, verbose_name='Дані конфігуратора')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('read', 'Переглянута'), ('in_progress', 'В роботі'), ('done', 'Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('crm_sent', models.BooleanField(default=False, verbose_name='Відправлено до CRM')),
                ('crm_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата відправки до CRM')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('dome_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='catalog.domemodel', verbose_name='Модель куполу')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
