# Generated by Django 5.2.15 on 2026-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='form_type',
            field=models.CharField(choices=[('hero', 'CTA Головна (hero)'), ('contact', 'Контакти'), ('about', 'Про компанію'), ('model', 'Заявка на модель'), ('configurator', 'Конфігуратор'), ('faq', 'FAQ fallback')], default='contact', max_length=20, verbose_name='Тип форми'),
        ),
    ]
