# Generated by Django 5.1.4 on 2026-06-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_sk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_cs', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_nl', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('area_m2', models.PositiveIntegerField(verbose_name='Площа, м²')),
                ('diameter', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Діаметр, м')),
                ('height_m', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Висота, м')),
                ('insulation_mm', models.PositiveIntegerField(default=200, verbose_name='Утеплення, мм')),
                ('purpose', models.CharField(choices=[('living', 'Проживання'), ('glamping', 'Глемпінг'), ('commercial', 'Комерція')], default='living', max_length=20, verbose_name='Призначення')),
                ('size_cat', models.CharField(choices=[('small', 'Малий'), ('medium', 'Середній'), ('large', 'Великий')], default='medium', max_length=10, verbose_name='Розмір')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('description_uk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_sk', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_cs', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_nl', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Короткий опис')),
                ('short_description_uk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткий опис')),
                ('short_description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткий опис')),
                ('short_description_sk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткий опис')),
                ('short_description_cs', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткий опис')),
                ('short_description_nl', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткий опис')),
                ('short_description_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткий опис')),
                ('short_description_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткий опис')),
                ('short_description_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткий опис')),
                ('price_base', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Ціна Базова, €')),
                ('price_standard', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Ціна Стандарт, €')),
                ('price_premium', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Ціна Преміум, €')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показувати на головній')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Модель куполу',
                'verbose_name_plural': 'Моделі куполів',
                'ordering': ['order', 'area_m2'],
            },
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/', verbose_name='Зображення')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головне')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('dome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.domemodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Зображення моделі',
                'verbose_name_plural': 'Зображення моделей',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ModelSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Характеристика')),
                ('key_uk', models.CharField(max_length=100, null=True, verbose_name='Характеристика')),
                ('key_en', models.CharField(max_length=100, null=True, verbose_name='Характеристика')),
                ('key_sk', models.CharField(max_length=100, null=True, verbose_name='Характеристика')),
                ('key_cs', models.CharField(max_length=100, null=True, verbose_name='Характеристика')),
                ('key_nl', models.CharField(max_length=100, null=True, verbose_name='Характеристика')),
                ('key_ru', models.CharField(max_length=100, null=True, verbose_name='Характеристика')),
                ('key_es', models.CharField(max_length=100, null=True, verbose_name='Характеристика')),
                ('key_fr', models.CharField(max_length=100, null=True, verbose_name='Характеристика')),
                ('value', models.CharField(max_length=200, verbose_name='Значення')),
                ('value_uk', models.CharField(max_length=200, null=True, verbose_name='Значення')),
                ('value_en', models.CharField(max_length=200, null=True, verbose_name='Значення')),
                ('value_sk', models.CharField(max_length=200, null=True, verbose_name='Значення')),
                ('value_cs', models.CharField(max_length=200, null=True, verbose_name='Значення')),
                ('value_nl', models.CharField(max_length=200, null=True, verbose_name='Значення')),
                ('value_ru', models.CharField(max_length=200, null=True, verbose_name='Значення')),
                ('value_es', models.CharField(max_length=200, null=True, verbose_name='Значення')),
                ('value_fr', models.CharField(max_length=200, null=True, verbose_name='Значення')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('dome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.domemodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ['order'],
            },
        ),
    ]
