# Generated by Django 5.2.15 on 2026-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domemodel',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/plans/', verbose_name='Планування (зображення)'),
        ),
        migrations.AddField(
            model_name='domemodel',
            name='floor_plan_note',
            field=models.TextField(blank=True, verbose_name='Планування (опис/схема)'),
        ),
        migrations.AddField(
            model_name='domemodel',
            name='floor_plan_note_cs',
            field=models.TextField(blank=True, null=True, verbose_name='Планування (опис/схема)'),
        ),
        migrations.AddField(
            model_name='domemodel',
            name='floor_plan_note_en',
            field=models.TextField(blank=True, null=True, verbose_name='Планування (опис/схема)'),
        ),
        migrations.AddField(
            model_name='domemodel',
            name='floor_plan_note_es',
            field=models.TextField(blank=True, null=True, verbose_name='Планування (опис/схема)'),
        ),
        migrations.AddField(
            model_name='domemodel',
            name='floor_plan_note_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Планування (опис/схема)'),
        ),
        migrations.AddField(
            model_name='domemodel',
            name='floor_plan_note_nl',
            field=models.TextField(blank=True, null=True, verbose_name='Планування (опис/схема)'),
        ),
        migrations.AddField(
            model_name='domemodel',
            name='floor_plan_note_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Планування (опис/схема)'),
        ),
        migrations.AddField(
            model_name='domemodel',
            name='floor_plan_note_sk',
            field=models.TextField(blank=True, null=True, verbose_name='Планування (опис/схема)'),
        ),
        migrations.AddField(
            model_name='domemodel',
            name='floor_plan_note_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Планування (опис/схема)'),
        ),
    ]
