# Generated by Django 5.2.15 on 2026-07-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_single_dome_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelimage',
            options={'ordering': ['-is_main', 'order'], 'verbose_name': 'Зображення моделі', 'verbose_name_plural': 'Зображення моделей'},
        ),
    ]
