# Generated by Django 5.1.4 on 2026-06-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_sk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_cs', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_nl', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категорія блогу',
                'verbose_name_plural': 'Категорії блогу',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=50, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Назва')),
                ('name_sk', models.CharField(max_length=50, null=True, verbose_name='Назва')),
                ('name_cs', models.CharField(max_length=50, null=True, verbose_name='Назва')),
                ('name_nl', models.CharField(max_length=50, null=True, verbose_name='Назва')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Назва')),
                ('name_es', models.CharField(max_length=50, null=True, verbose_name='Назва')),
                ('name_fr', models.CharField(max_length=50, null=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_uk', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_sk', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_cs', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_nl', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_fr', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Анонс')),
                ('excerpt_uk', models.TextField(blank=True, max_length=500, null=True, verbose_name='Анонс')),
                ('excerpt_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='Анонс')),
                ('excerpt_sk', models.TextField(blank=True, max_length=500, null=True, verbose_name='Анонс')),
                ('excerpt_cs', models.TextField(blank=True, max_length=500, null=True, verbose_name='Анонс')),
                ('excerpt_nl', models.TextField(blank=True, max_length=500, null=True, verbose_name='Анонс')),
                ('excerpt_ru', models.TextField(blank=True, max_length=500, null=True, verbose_name='Анонс')),
                ('excerpt_es', models.TextField(blank=True, max_length=500, null=True, verbose_name='Анонс')),
                ('excerpt_fr', models.TextField(blank=True, max_length=500, null=True, verbose_name='Анонс')),
                ('body', models.TextField(verbose_name='Контент (HTML)')),
                ('body_uk', models.TextField(null=True, verbose_name='Контент (HTML)')),
                ('body_en', models.TextField(null=True, verbose_name='Контент (HTML)')),
                ('body_sk', models.TextField(null=True, verbose_name='Контент (HTML)')),
                ('body_cs', models.TextField(null=True, verbose_name='Контент (HTML)')),
                ('body_nl', models.TextField(null=True, verbose_name='Контент (HTML)')),
                ('body_ru', models.TextField(null=True, verbose_name='Контент (HTML)')),
                ('body_es', models.TextField(null=True, verbose_name='Контент (HTML)')),
                ('body_fr', models.TextField(null=True, verbose_name='Контент (HTML)')),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Обкладинка')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='SEO заголовок')),
                ('seo_title_uk', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO заголовок')),
                ('seo_title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO заголовок')),
                ('seo_title_sk', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO заголовок')),
                ('seo_title_cs', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO заголовок')),
                ('seo_title_nl', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO заголовок')),
                ('seo_title_ru', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO заголовок')),
                ('seo_title_es', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO заголовок')),
                ('seo_title_fr', models.CharField(blank=True, max_length=70, null=True, verbose_name='SEO заголовок')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='SEO опис')),
                ('seo_description_uk', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO опис')),
                ('seo_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO опис')),
                ('seo_description_sk', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO опис')),
                ('seo_description_cs', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO опис')),
                ('seo_description_nl', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO опис')),
                ('seo_description_ru', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO опис')),
                ('seo_description_es', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO опис')),
                ('seo_description_fr', models.CharField(blank=True, max_length=160, null=True, verbose_name='SEO опис')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Категорія')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
