# Generated by Django 5.1.4 on 2026-06-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Підпис')),
                ('title_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Підпис')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Підпис')),
                ('title_sk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Підпис')),
                ('title_cs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Підпис')),
                ('title_nl', models.CharField(blank=True, max_length=200, null=True, verbose_name='Підпис')),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Підпис')),
                ('title_es', models.CharField(blank=True, max_length=200, null=True, verbose_name='Підпис')),
                ('title_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Підпис')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фото')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('alt_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст')),
                ('alt_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст')),
                ('alt_sk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст')),
                ('alt_cs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст')),
                ('alt_nl', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст')),
                ('alt_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст')),
                ('alt_es', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст')),
                ('alt_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt текст')),
                ('project_type', models.CharField(choices=[('glamping', 'Глемпінг'), ('living', 'Проживання'), ('commercial', 'Комерція')], default='living', max_length=20, verbose_name='Тип проєкту')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Фото галереї',
                'verbose_name_plural': 'Галерея',
                'ordering': ['order', '-pk'],
            },
        ),
    ]
