# Generated by Django 5.2.15 on 2026-09-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='category',
            field=models.CharField(choices=[('dome', 'Купол'), ('production', 'Виробництво')], default='dome', max_length=20, verbose_name='Блок галереї'),
        ),
    ]
