# Generated by Django 5.2.15 on 2026-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Ім'я та прізвище")),
                ('position', models.CharField(max_length=150, verbose_name='Посада')),
                ('position_uk', models.CharField(max_length=150, null=True, verbose_name='Посада')),
                ('position_en', models.CharField(max_length=150, null=True, verbose_name='Посада')),
                ('position_sk', models.CharField(max_length=150, null=True, verbose_name='Посада')),
                ('position_cs', models.CharField(max_length=150, null=True, verbose_name='Посада')),
                ('position_nl', models.CharField(max_length=150, null=True, verbose_name='Посада')),
                ('position_ru', models.CharField(max_length=150, null=True, verbose_name='Посада')),
                ('position_es', models.CharField(max_length=150, null=True, verbose_name='Посада')),
                ('position_fr', models.CharField(max_length=150, null=True, verbose_name='Посада')),
                ('photo', models.ImageField(blank=True, upload_to='team/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
            ],
            options={
                'verbose_name': 'Член команди',
                'verbose_name_plural': 'Команда',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
