# Generated by Django 5.1.4 on 2026-06-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(blank=True, max_length=100, verbose_name='Графік роботи')),
                ('crm_webhook_url', models.URLField(blank=True, verbose_name='CRM Webhook URL')),
                ('ga4_measurement_id', models.CharField(blank=True, max_length=50, verbose_name='GA4 Measurement ID')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('company_name', models.CharField(default='KUPOLLA', max_length=100, verbose_name='Назва компанії')),
                ('company_code', models.CharField(blank=True, max_length=20, verbose_name='Код ЄДРПОУ')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='ПДВ / ІПН')),
                ('privacy_policy_url', models.CharField(blank=True, max_length=255, verbose_name='URL Політики конфіденційності')),
                ('terms_url', models.CharField(blank=True, max_length=255, verbose_name='URL Умов використання')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
