# Generated by Django 5.2.15 on 2026-06-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='OpenStreetMap або Google Maps embed URL', verbose_name='URL карти (embed)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.URLField(blank=True, verbose_name='WhatsApp'),
        ),
    ]
