# Generated by Django 5.2.15 on 2026-09-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone_eu',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон (Європа та інші країни)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон (Україна)'),
        ),
    ]
