# Generated by Django 5.2.15 on 2026-09-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_full_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_drive_url',
            field=models.URLField(
                blank=True,
                help_text='Матеріали / фото для сторінки Контакти',
                verbose_name='Посилання на Google Drive',
            ),
        ),
    ]
