# Generated by Django 5.1.4 on 2026-06-15 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тема')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Тема')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Тема')),
                ('name_sk', models.CharField(max_length=100, null=True, verbose_name='Тема')),
                ('name_cs', models.CharField(max_length=100, null=True, verbose_name='Тема')),
                ('name_nl', models.CharField(max_length=100, null=True, verbose_name='Тема')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Тема')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Тема')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Тема')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Група FAQ',
                'verbose_name_plural': 'Групи FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Питання')),
                ('question_uk', models.CharField(max_length=300, null=True, verbose_name='Питання')),
                ('question_en', models.CharField(max_length=300, null=True, verbose_name='Питання')),
                ('question_sk', models.CharField(max_length=300, null=True, verbose_name='Питання')),
                ('question_cs', models.CharField(max_length=300, null=True, verbose_name='Питання')),
                ('question_nl', models.CharField(max_length=300, null=True, verbose_name='Питання')),
                ('question_ru', models.CharField(max_length=300, null=True, verbose_name='Питання')),
                ('question_es', models.CharField(max_length=300, null=True, verbose_name='Питання')),
                ('question_fr', models.CharField(max_length=300, null=True, verbose_name='Питання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('answer_uk', models.TextField(null=True, verbose_name='Відповідь')),
                ('answer_en', models.TextField(null=True, verbose_name='Відповідь')),
                ('answer_sk', models.TextField(null=True, verbose_name='Відповідь')),
                ('answer_cs', models.TextField(null=True, verbose_name='Відповідь')),
                ('answer_nl', models.TextField(null=True, verbose_name='Відповідь')),
                ('answer_ru', models.TextField(null=True, verbose_name='Відповідь')),
                ('answer_es', models.TextField(null=True, verbose_name='Відповідь')),
                ('answer_fr', models.TextField(null=True, verbose_name='Відповідь')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='faq.faqgroup', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Питання FAQ',
                'verbose_name_plural': 'Питання FAQ',
                'ordering': ['order'],
            },
        ),
    ]
