# Generated by Django 5.1.4 on 2026-06-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('model', 'Базова модель'), ('diameter', 'Діаметр'), ('tier', 'Комплектація'), ('addon', 'Опція (додатково)')], max_length=20, verbose_name='Тип опції')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('name_uk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_sk', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_cs', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_nl', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Назва')),
                ('price_delta', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Надбавка, €')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Базова ціна, €')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Опція конфігуратора',
                'verbose_name_plural': 'Опції конфігуратора',
                'ordering': ['option_type', 'order'],
            },
        ),
    ]
